# Generated by Django 3.2.22 on 2023-10-11 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_no', models.CharField(max_length=15, null=True, unique=True)),
                ('contract_start_date', models.DateField(null=True)),
                ('contract_end_date', models.DateField(null=True)),
                ('phone_number', models.CharField(max_length=10, null=True, unique=True)),
                ('profile_pic', models.ImageField(default='images/default.avif', upload_to='profile_pic')),
                ('state', models.CharField(max_length=30, null=True)),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('remaining_budget', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('budget_added', models.DateField(auto_now_add=True)),
                ('budget_modified', models.DateField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.employee')),
            ],
        ),
    ]
