# Generated by Django 3.2.22 on 2023-10-12 10:04

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('contract_no', models.CharField(max_length=15, unique=True)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('profile_pic', models.ImageField(default='images/default.avif', upload_to='profile_pic')),
                ('state', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('remaining_budget', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('budget_added', models.DateField(auto_now_add=True)),
                ('budget_modified', models.DateField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AdvanceTripPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=10)),
                ('year', models.CharField(default='2023', max_length=20, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('trip_plan', models.FileField(upload_to=account.models.get_upload_path)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.employee')),
            ],
        ),
    ]
