# Generated by Django 3.2.22 on 2023-10-11 12:14

import account.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.employee'),
        ),
        migrations.CreateModel(
            name='AdvanceTripPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('trip_plan', models.FileField(upload_to=account.models.user_directory_path)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.employee')),
            ],
        ),
    ]
