# Generated by Django 3.2.22 on 2023-10-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_start_date',
            field=models.DateField(null=True),
        ),
    ]
