# Generated by Django 3.2.22 on 2023-10-11 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20231011_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancetripplan',
            name='employee',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='account.employee'),
        ),
    ]
