# Generated by Django 3.2.22 on 2023-10-11 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_advancetripplan_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancetripplan',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.employee'),
        ),
    ]
