# Generated by Django 3.2.22 on 2023-10-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_employee_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user_permissions',
        ),
    ]
