# Generated by Django 3.2.22 on 2023-10-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_employee_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contract_no',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
