# Generated by Django 3.2.22 on 2023-10-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
